### ISSUE TITLE
Source for ipp-v3-java-devkit-2.3.4-jar-with-dependencies.jar ?

### ISSUE THREAD

**Issue by chothia** [IntuitDeveloper/SampleApp-ECommerce_Payments_SalesReceipt-Java#1]
Hi

Where can I find the source for ipp-v3-java-devkit-2.3.4-jar-with-dependencies.jar ?

From https://developer.intuit.com/docs/0100_accounting/0500_developer_kits/0201_ipp_java_devkit_3.0 I only get version 2.3.2.

Thanks

**Comment by wentaointu** [comment]
You should be able to find the source code at https://github.com/IntuitDeveloper/V3-Java-SDK

**Comment by chothia** [comment]
I get a 404 when I click on that link.

I also tried to browse to it from https://github.com/IntuitDeveloper but I don't see it there.

Is the project private?

**Comment by sanju1989** [comment]
I am getting 404.

**Comment by diana-derose** [comment]
Java SDK is not open sourced at this time. Link to the latest version of the SDK is available here: 
https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_accounting/0200_java/0002_installing_the_java_sdk_for_quickbooks
