### ISSUE TITLE
Where is Payments SDK?

### ISSUE THREAD

**Issue by wendelicious** [IntuitDeveloper/SampleApp-ECommerce_Payments_SalesReceipt-Java#3]
I see that there is the [`payments-reference-implementation`](https://github.com/IntuitDeveloper/SampleApp-ECommerce_Payments_SalesReceipt-Java/tree/master/libs/payments-reference-implementation) project embedded in this project, but I can't seem to find where the Payments SDK/lib _should_ be coming from.

The [tutorial online](https://developer.intuit.com/v2/ui#/emulator?workflow=ecommerce) shows using the `Charge` class, which seems to come from the `com.intuit.sample.payment.model` package, which isn't readily avialable in the [`ipp-v3-java-data` project](https://github.com/intuit/QuickBooks-V3-Java-SDK/tree/develop/ipp-v3-java-data/src/main/java/com/intuit/ipp/data).  [Maven Central](https://search.maven.org/#search%7Cga%7C1%7Ccom.intuit.quickbooks-online) doesn't seem to have any other artifacts for me to depend on.

So, what is the right way to do this?  Are the examples wrong?  Is the SDK intended to be embedded like this?  There is no path to green for me, shy of [re-implementing the REST interface](https://github.com/IntuitDeveloper/SampleApp-Payments-Java/blob/master/src/main/java/com/intuit/sample/payment/helper/PaymentHelper.java), which is a terrible answer.

Cross-posting, as I don't know where the "best" place to reach QBO developer support.

**Comment by diana-derose** [comment]
Hi @wendelicious  - We currently don't have a Payments SDK, however, you can copy the contents under "payments-reference-implementation" folder and use it within your app. The latest version of devkit and data libraries can be downloaded from maven, if you are using Accounting APIS as well. https://search.maven.org/#search%7Cga%7C1%7Ccom.intuit.quickbooks-online

**Comment by wendelicious** [comment]
@diana-derose I'm happy to do that if that is the recommended way about it.

Can I ask why Payments isn't in the SDK?  Is it an API I shouldn't be using?  Is there another way to do this?

**Comment by wendelicious** [comment]
Also, what does QBO have for a credit card vault?  The use case is to store a credit card for reuse - similar to recurring, but on-demand rather than on schedule.  I'd like to vault it elsewhere and only save the CC token.

**Comment by diana-derose** [comment]
Hi @wendelicious - Payments SDK is not prioritized yet but the API is fully functional and can be used.
Regarding your other question, you can use the card endpoint to store the credit card information
https://developer.intuit.com/docs/api/payments/cards

And then use the Card->id from the response as a value for "cardOnFile" field while creating charge.
https://developer.intuit.com/docs/api/payments/charges

**Comment by diana-derose** [comment]
Also, you can post questions in our forum https://help.developer.intuit.com/s/
